#!/usr/bin/env bash
# shellcheck disable=SC2086
# display information about subdomains.
if [ $# -eq 1 ]; then
    sub_domains='www lb-01 web-01 web-02'
else
    sub_domains="$2"
fi

for sub in $sub_domains; do
    echo -n "The subdomain $sub"
    # Get dig output and filter for the record type and destination
    dig_output=$(dig +short "$sub.$1")
    
    # Check if there is output from dig
    if [ -n "$dig_output" ]; then
        record_type=$(echo "$dig_output" | awk '{print $1}')
        destination=$(echo "$dig_output" | awk '{print $2}')
        echo " is a $record_type record and points to $destination"
    else
        echo " does not exist"
    fi
done
